[package]
name = "pulsar-client"
version = "0.1.0"
authors = ["Alex Mault <amault@developers.wyyerd.com>"]

[dependencies]
bytes = "0.4.0"
crc = "1.0.0"
failure = "0.1.0"
futures = "0.1.23"
nom = "4.0.0"
prost = "0.4.0"
prost-derive = "0.4.0"
tokio = "0.1.11"

[build-dependencies]
prost-build = "0.4.0"
